-- =====================================================-- =====================================================

-- ROLLBACK Script for V1.1, V1.2, V1.3-- ROLLBACK Script for V1.1, V1.2, V1.3

-- Purpose: Undo all Phase 1 migrations if needed-- Purpose: Undo all Phase 1 migrations if needed

-- Date: 2025-11-18-- Date: 2025-11-17

-- Database: SQL Server-- WARNING: This will remove all data in new columns!

-- WARNING: This will remove all data in new columns!-- =====================================================

-- =====================================================

-- ROLLBACK V1.3: Drop TOURNAMENT_GALLERY table

-- ROLLBACK V1.3: Drop TOURNAMENT_GALLERY tableDROP TABLE IF EXISTS TOURNAMENT_GALLERY;

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'TOURNAMENT_GALLERY') AND type in (N'U'))

    DROP TABLE TOURNAMENT_GALLERY;-- ROLLBACK V1.2: Remove columns from NGUOI_DUNG

GOALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS EMAIL;

ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS DIEN_THOAI;

-- ROLLBACK V1.2: Remove columns from NGUOI_DUNGALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS VAI_TRO;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'NGAY_HET_HAN_TOKEN')ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS TRANG_THAI;

    ALTER TABLE NGUOI_DUNG DROP COLUMN NGAY_HET_HAN_TOKEN;ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS LAN_DANG_NHAP_CUOI;

ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS ANH_DAI_DIEN;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'MA_DAT_LAI_MK')ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS XAC_THUC_EMAIL;

    ALTER TABLE NGUOI_DUNG DROP COLUMN MA_DAT_LAI_MK;ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS MA_XAC_THUC;

ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS MA_DAT_LAI_MK;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'MA_XAC_THUC')ALTER TABLE NGUOI_DUNG DROP COLUMN IF EXISTS NGAY_HET_HAN_TOKEN;

    ALTER TABLE NGUOI_DUNG DROP COLUMN MA_XAC_THUC;

-- Drop indexes for NGUOI_DUNG

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'XAC_THUC_EMAIL')DROP INDEX IF EXISTS idx_nguoi_dung_email ON NGUOI_DUNG;

    ALTER TABLE NGUOI_DUNG DROP COLUMN XAC_THUC_EMAIL;DROP INDEX IF EXISTS idx_nguoi_dung_vai_tro ON NGUOI_DUNG;

DROP INDEX IF EXISTS idx_nguoi_dung_trang_thai ON NGUOI_DUNG;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'ANH_DAI_DIEN')

    ALTER TABLE NGUOI_DUNG DROP COLUMN ANH_DAI_DIEN;-- ROLLBACK V1.1: Remove columns from GIAI_DAU

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS MO_TA;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'LAN_DANG_NHAP_CUOI')ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS DIA_DIEM;

    ALTER TABLE NGUOI_DUNG DROP COLUMN LAN_DANG_NHAP_CUOI;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS TINH_THANH;

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS QUOC_GIA;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'TRANG_THAI')ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS TRANG_THAI;

    ALTER TABLE NGUOI_DUNG DROP COLUMN TRANG_THAI;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS NOI_BAT;

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS HINH_ANH;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'VAI_TRO')ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS LOGO;

    ALTER TABLE NGUOI_DUNG DROP COLUMN VAI_TRO;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS NGAY_MO_DANG_KI;

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS NGAY_DONG_DANG_KI;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'DIEN_THOAI')ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS SO_LUONG_TOI_DA;

    ALTER TABLE NGUOI_DUNG DROP COLUMN DIEN_THOAI;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS PHI_THAM_GIA;

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS GIAI_THUONG;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'NGUOI_DUNG') AND name = 'EMAIL')ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS DIEN_THOAI;

    ALTER TABLE NGUOI_DUNG DROP COLUMN EMAIL;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS EMAIL;

GOALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS WEBSITE;

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS CAP_DO;

-- Drop indexes for NGUOI_DUNGALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS THE_LOAI;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_nguoi_dung_email' AND object_id = OBJECT_ID('NGUOI_DUNG'))ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS SAN_THI_DAU;

    DROP INDEX idx_nguoi_dung_email ON NGUOI_DUNG;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS QUY_DINH;

ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS LUOT_XEM;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_nguoi_dung_vai_tro' AND object_id = OBJECT_ID('NGUOI_DUNG'))ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS DANH_GIA_TB;

    DROP INDEX idx_nguoi_dung_vai_tro ON NGUOI_DUNG;ALTER TABLE GIAI_DAU DROP COLUMN IF EXISTS TONG_DANH_GIA;



IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_nguoi_dung_trang_thai' AND object_id = OBJECT_ID('NGUOI_DUNG'))-- Drop indexes for GIAI_DAU

    DROP INDEX idx_nguoi_dung_trang_thai ON NGUOI_DUNG;DROP INDEX IF EXISTS idx_giai_dau_trang_thai ON GIAI_DAU;

DROP INDEX IF EXISTS idx_giai_dau_noi_bat ON GIAI_DAU;

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'UQ' AND name = 'unique_email')DROP INDEX IF EXISTS idx_giai_dau_ngay_bd ON GIAI_DAU;

    ALTER TABLE NGUOI_DUNG DROP CONSTRAINT unique_email;DROP INDEX IF EXISTS idx_giai_dau_ngay_kt ON GIAI_DAU;

GODROP INDEX IF EXISTS idx_giai_dau_tinh_thanh ON GIAI_DAU;



-- ROLLBACK V1.1: Remove columns from GIAI_DAUCOMMIT;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'TONG_DANH_GIA')

    ALTER TABLE GIAI_DAU DROP COLUMN TONG_DANH_GIA;-- =====================================================

-- NOTE: Only run this if you need to completely undo

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'DANH_GIA_TB')-- Phase 1 migrations. Make sure to backup data first!

    ALTER TABLE GIAI_DAU DROP COLUMN DANH_GIA_TB;-- =====================================================


IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'LUOT_XEM')
    ALTER TABLE GIAI_DAU DROP COLUMN LUOT_XEM;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'QUY_DINH')
    ALTER TABLE GIAI_DAU DROP COLUMN QUY_DINH;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'SAN_THI_DAU')
    ALTER TABLE GIAI_DAU DROP COLUMN SAN_THI_DAU;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'THE_LOAI')
    ALTER TABLE GIAI_DAU DROP COLUMN THE_LOAI;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'CAP_DO')
    ALTER TABLE GIAI_DAU DROP COLUMN CAP_DO;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'WEBSITE')
    ALTER TABLE GIAI_DAU DROP COLUMN WEBSITE;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'EMAIL')
    ALTER TABLE GIAI_DAU DROP COLUMN EMAIL;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'DIEN_THOAI')
    ALTER TABLE GIAI_DAU DROP COLUMN DIEN_THOAI;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'GIAI_THUONG')
    ALTER TABLE GIAI_DAU DROP COLUMN GIAI_THUONG;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'PHI_THAM_GIA')
    ALTER TABLE GIAI_DAU DROP COLUMN PHI_THAM_GIA;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'SO_LUONG_TOI_DA')
    ALTER TABLE GIAI_DAU DROP COLUMN SO_LUONG_TOI_DA;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'NGAY_DONG_DANG_KI')
    ALTER TABLE GIAI_DAU DROP COLUMN NGAY_DONG_DANG_KI;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'NGAY_MO_DANG_KI')
    ALTER TABLE GIAI_DAU DROP COLUMN NGAY_MO_DANG_KI;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'LOGO')
    ALTER TABLE GIAI_DAU DROP COLUMN LOGO;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'HINH_ANH')
    ALTER TABLE GIAI_DAU DROP COLUMN HINH_ANH;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'NOI_BAT')
    ALTER TABLE GIAI_DAU DROP COLUMN NOI_BAT;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'TRANG_THAI')
    ALTER TABLE GIAI_DAU DROP COLUMN TRANG_THAI;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'QUOC_GIA')
    ALTER TABLE GIAI_DAU DROP COLUMN QUOC_GIA;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'TINH_THANH')
    ALTER TABLE GIAI_DAU DROP COLUMN TINH_THANH;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'DIA_DIEM')
    ALTER TABLE GIAI_DAU DROP COLUMN DIA_DIEM;

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'GIAI_DAU') AND name = 'MO_TA')
    ALTER TABLE GIAI_DAU DROP COLUMN MO_TA;
GO

-- Drop indexes for GIAI_DAU
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_giai_dau_trang_thai' AND object_id = OBJECT_ID('GIAI_DAU'))
    DROP INDEX idx_giai_dau_trang_thai ON GIAI_DAU;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_giai_dau_noi_bat' AND object_id = OBJECT_ID('GIAI_DAU'))
    DROP INDEX idx_giai_dau_noi_bat ON GIAI_DAU;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_giai_dau_ngay_bd' AND object_id = OBJECT_ID('GIAI_DAU'))
    DROP INDEX idx_giai_dau_ngay_bd ON GIAI_DAU;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_giai_dau_ngay_kt' AND object_id = OBJECT_ID('GIAI_DAU'))
    DROP INDEX idx_giai_dau_ngay_kt ON GIAI_DAU;

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_giai_dau_tinh_thanh' AND object_id = OBJECT_ID('GIAI_DAU'))
    DROP INDEX idx_giai_dau_tinh_thanh ON GIAI_DAU;
GO

-- =====================================================
-- NOTE: Only run this if you need to completely undo
-- Phase 1 migrations. Make sure to backup data first!
-- =====================================================
